using System.Text.Json.Serialization;
namespace RadarTendencias.Api.Features.DTOs;

public class MonitoramentoDTO { public int FranquiaID { get; set; } public decimal HypeScore { get; set; } public int VolumeMencoes { get; set; } public decimal SentimentoPositivo { get; set; } public string? ResumoIA { get; set; } }
public class SyncFranquiaDTO { public string Nome { get; set; } = string.Empty; public int CategoriaID { get; set; } public List<string> Tags { get; set; } = new(); public int? ExternalID { get; set; } public string? Sinopse { get; set; } public string? ImagemUrl { get; set; } public double? ScoreInicial { get; set; } public string Fonte { get; set; } = "Desconhecida"; }
public class FluxoDTO { public int FluxoID { get; set; } public string Nome { get; set; } = string.Empty; public List<NodeDTO> Nodes { get; set; } = new(); public List<ConnectionDTO> Connections { get; set; } = new(); }
public class NodeDTO { public string NodeID { get; set; } = string.Empty; public string Tipo { get; set; } = string.Empty; public string Label { get; set; } = string.Empty; public int PosX { get; set; } public int PosY { get; set; } }
public class ConnectionDTO { public string ConnectionID { get; set; } = string.Empty; public string SourceNodeID { get; set; } = string.Empty; public string SourcePortID { get; set; } = string.Empty; public string TargetNodeID { get; set; } = string.Empty; public string TargetPortID { get; set; } = string.Empty; }
public class AlertaDTO { public int FranquiaID { get; set; } public int FluxoID { get; set; } public string Mensagem { get; set; } = string.Empty; }
public class PersonagemDTO { public string Nome { get; set; } = string.Empty; public string Papel { get; set; } = string.Empty; public string ImagemUrl { get; set; } = string.Empty; }
public class JikanSearchResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public List<JikanAnime>? Data { get; set; } }
public class JikanCharactersResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public List<JikanCharacterData>? Data { get; set; } }
public class JikanCharacterData { [System.Text.Json.Serialization.JsonPropertyName("character")] public JikanCharacter? Character { get; set; } [System.Text.Json.Serialization.JsonPropertyName("role")] public string? Role { get; set; } }
public class JikanCharacter { [System.Text.Json.Serialization.JsonPropertyName("name")] public string? Name { get; set; } [System.Text.Json.Serialization.JsonPropertyName("images")] public JikanCharacterImages? Images { get; set; } }
public class JikanCharacterImages { [System.Text.Json.Serialization.JsonPropertyName("jpg")] public JikanCharacterJpg? Jpg { get; set; } }
public class JikanCharacterJpg { [System.Text.Json.Serialization.JsonPropertyName("image_url")] public string? ImageUrl { get; set; } }
public class TmdbSearchResponse { [System.Text.Json.Serialization.JsonPropertyName("results")] public List<TmdbMedia>? Results { get; set; } }
public class TmdbWatchProvidersResponse { [System.Text.Json.Serialization.JsonPropertyName("results")] public Dictionary<string, TmdbWatchProviderRegion>? Results { get; set; } }
public class TmdbWatchProviderRegion { [System.Text.Json.Serialization.JsonPropertyName("flatrate")] public List<TmdbProviderItem>? Flatrate { get; set; } [System.Text.Json.Serialization.JsonPropertyName("free")] public List<TmdbProviderItem>? Free { get; set; } [System.Text.Json.Serialization.JsonPropertyName("buy")] public List<TmdbProviderItem>? Buy { get; set; } }
public class TmdbProviderItem { [System.Text.Json.Serialization.JsonPropertyName("provider_id")] public int ProviderId { get; set; } [System.Text.Json.Serialization.JsonPropertyName("provider_name")] public string? ProviderName { get; set; } [System.Text.Json.Serialization.JsonPropertyName("logo_path")] public string? LogoPath { get; set; } }
public class TmdbCreditsResponse { [System.Text.Json.Serialization.JsonPropertyName("cast")] public List<TmdbCast>? Cast { get; set; } }
public class TmdbCast { [System.Text.Json.Serialization.JsonPropertyName("name")] public string? Name { get; set; } [System.Text.Json.Serialization.JsonPropertyName("character")] public string? Character { get; set; } [System.Text.Json.Serialization.JsonPropertyName("profile_path")] public string? ProfilePath { get; set; } }
public class JikanAnime { [System.Text.Json.Serialization.JsonPropertyName("mal_id")] public int MalId { get; set; } [System.Text.Json.Serialization.JsonPropertyName("title")] public string? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("score")] public double? Score { get; set; } [System.Text.Json.Serialization.JsonPropertyName("members")] public int Members { get; set; } [System.Text.Json.Serialization.JsonPropertyName("synopsis")] public string? Synopsis { get; set; } [System.Text.Json.Serialization.JsonPropertyName("genres")] public List<JikanGenre>? Genres { get; set; } [System.Text.Json.Serialization.JsonPropertyName("images")] public JikanImages? Images { get; set; } }
public class JikanGenre { [System.Text.Json.Serialization.JsonPropertyName("name")] public string? Name { get; set; } }
public class JikanImages { [System.Text.Json.Serialization.JsonPropertyName("jpg")] public JikanJpg? Jpg { get; set; } }
public class JikanJpg { [System.Text.Json.Serialization.JsonPropertyName("image_url")] public string? ImageUrl { get; set; } }
public class TmdbMedia { [System.Text.Json.Serialization.JsonPropertyName("id")] public int Id { get; set; } [System.Text.Json.Serialization.JsonPropertyName("title")] public string? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("name")] public string? Name { get; set; } [System.Text.Json.Serialization.JsonPropertyName("vote_average")] public double VoteAverage { get; set; } [System.Text.Json.Serialization.JsonPropertyName("vote_count")] public int VoteCount { get; set; } [System.Text.Json.Serialization.JsonPropertyName("overview")] public string? Overview { get; set; } [System.Text.Json.Serialization.JsonPropertyName("media_type")] public string? MediaType { get; set; } [System.Text.Json.Serialization.JsonPropertyName("poster_path")] public string? PosterPath { get; set; } }
public class RedditResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public RedditData? Data { get; set; } }
public class RedditData { [System.Text.Json.Serialization.JsonPropertyName("children")] public List<RedditChild>? Children { get; set; } }
public class RedditChild { [System.Text.Json.Serialization.JsonPropertyName("data")] public RedditPostData? Data { get; set; } }
public class ComunidadeFeedbackDTO { public string Fonte { get; set; } = string.Empty; public string Autor { get; set; } = string.Empty; public string Titulo { get; set; } = string.Empty; public string Texto { get; set; } = string.Empty; public string Url { get; set; } = string.Empty; }
public class RedditPostData { [System.Text.Json.Serialization.JsonPropertyName("title")] public string? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("selftext")] public string? Selftext { get; set; } [System.Text.Json.Serialization.JsonPropertyName("author")] public string? Author { get; set; } [System.Text.Json.Serialization.JsonPropertyName("permalink")] public string? Permalink { get; set; } }
public class JikanReviewsResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public List<JikanReview>? Data { get; set; } }
public class JikanReview { [System.Text.Json.Serialization.JsonPropertyName("review")] public string? ReviewText { get; set; } [System.Text.Json.Serialization.JsonPropertyName("url")] public string? Url { get; set; } [System.Text.Json.Serialization.JsonPropertyName("user")] public JikanUser? User { get; set; } }
public class JikanUser { [System.Text.Json.Serialization.JsonPropertyName("username")] public string? Username { get; set; } }
public class TmdbReviewsResponse { [System.Text.Json.Serialization.JsonPropertyName("results")] public List<TmdbReview>? Results { get; set; } }
public class TmdbReview { [System.Text.Json.Serialization.JsonPropertyName("content")] public string? Content { get; set; } [System.Text.Json.Serialization.JsonPropertyName("author")] public string? Author { get; set; } [System.Text.Json.Serialization.JsonPropertyName("url")] public string? Url { get; set; } }
public class FranquiaDbResult { public string Nome { get; set; } = string.Empty; public int CategoriaID { get; set; } public int? ExternalID { get; set; } public string? TagsString { get; set; } }
public class YoutubeSearchResponse { [System.Text.Json.Serialization.JsonPropertyName("items")] public List<YoutubeItem>? Items { get; set; } }
public class YoutubeItem { [System.Text.Json.Serialization.JsonPropertyName("id")] public YoutubeId? Id { get; set; } [System.Text.Json.Serialization.JsonPropertyName("snippet")] public YoutubeSnippet? Snippet { get; set; } }
public class YoutubeId { [System.Text.Json.Serialization.JsonPropertyName("videoId")] public string? VideoId { get; set; } }
public class YoutubeSnippet { [System.Text.Json.Serialization.JsonPropertyName("title")] public string? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("description")] public string? Description { get; set; } [System.Text.Json.Serialization.JsonPropertyName("channelTitle")] public string? ChannelTitle { get; set; } }
public class AnilistResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public AnilistData? Data { get; set; } }
public class AnilistData { [System.Text.Json.Serialization.JsonPropertyName("Page")] public AnilistPage? Page { get; set; } }
public class AnilistPage { [System.Text.Json.Serialization.JsonPropertyName("media")] public List<AnilistMedia>? Media { get; set; } }
public class AnilistMedia { [System.Text.Json.Serialization.JsonPropertyName("id")] public int Id { get; set; } [System.Text.Json.Serialization.JsonPropertyName("title")] public AnilistTitle? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("coverImage")] public AnilistCoverImage? CoverImage { get; set; } [System.Text.Json.Serialization.JsonPropertyName("description")] public string? Description { get; set; } [System.Text.Json.Serialization.JsonPropertyName("genres")] public List<string>? Genres { get; set; } [System.Text.Json.Serialization.JsonPropertyName("averageScore")] public double? AverageScore { get; set; } }
public class AnilistTitle { [System.Text.Json.Serialization.JsonPropertyName("romaji")] public string? Romaji { get; set; } [System.Text.Json.Serialization.JsonPropertyName("english")] public string? English { get; set; } }
public class AnilistCoverImage { [System.Text.Json.Serialization.JsonPropertyName("large")] public string? Large { get; set; } }
public class AnilistSeasonResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public AnilistSeasonData? Data { get; set; } }
public class AnilistSeasonData { [System.Text.Json.Serialization.JsonPropertyName("Page")] public AnilistSeasonPage? Page { get; set; } }
public class AnilistSeasonPage { [System.Text.Json.Serialization.JsonPropertyName("media")] public List<AnilistSeasonMedia>? Media { get; set; } }
public class AnilistSeasonMedia { [System.Text.Json.Serialization.JsonPropertyName("id")] public int Id { get; set; } [System.Text.Json.Serialization.JsonPropertyName("title")] public AnilistTitle? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("coverImage")] public AnilistCoverImage? CoverImage { get; set; } [System.Text.Json.Serialization.JsonPropertyName("popularity")] public int Popularity { get; set; } [System.Text.Json.Serialization.JsonPropertyName("averageScore")] public double? AverageScore { get; set; } [System.Text.Json.Serialization.JsonPropertyName("trending")] public int Trending { get; set; } [System.Text.Json.Serialization.JsonPropertyName("genres")] public List<string>? Genres { get; set; } }
public class AnilistRelationsResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public AnilistRelationsData? Data { get; set; } }
public class AnilistRelationsData { [System.Text.Json.Serialization.JsonPropertyName("Media")] public AnilistMediaRelations? Media { get; set; } }
public class AnilistMediaRelations { [System.Text.Json.Serialization.JsonPropertyName("relations")] public AnilistRelationsContainer? Relations { get; set; } }
public class AnilistRelationsContainer { [System.Text.Json.Serialization.JsonPropertyName("edges")] public List<AnilistRelationEdge>? Edges { get; set; } }
public class AnilistRelationEdge { [System.Text.Json.Serialization.JsonPropertyName("relationType")] public string? RelationType { get; set; } [System.Text.Json.Serialization.JsonPropertyName("node")] public AnilistRelationNode? Node { get; set; } }
public class AnilistRelationNode { [System.Text.Json.Serialization.JsonPropertyName("id")] public int Id { get; set; } [System.Text.Json.Serialization.JsonPropertyName("title")] public AnilistTitle? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("type")] public string? Type { get; set; } [System.Text.Json.Serialization.JsonPropertyName("coverImage")] public AnilistCoverImage? CoverImage { get; set; } }
public class AnilistScheduleResponse { [System.Text.Json.Serialization.JsonPropertyName("data")] public AnilistScheduleData? Data { get; set; } }
public class AnilistScheduleData { [System.Text.Json.Serialization.JsonPropertyName("Page")] public AnilistSchedulePage? Page { get; set; } }
public class AnilistSchedulePage { [System.Text.Json.Serialization.JsonPropertyName("airingSchedules")] public List<AiringScheduleItem>? AiringSchedules { get; set; } }
public class AiringScheduleItem { [System.Text.Json.Serialization.JsonPropertyName("airingAt")] public long AiringAt { get; set; } [System.Text.Json.Serialization.JsonPropertyName("episode")] public int Episode { get; set; } [System.Text.Json.Serialization.JsonPropertyName("media")] public AnilistScheduleMedia? Media { get; set; } }
public class AnilistScheduleMedia { [System.Text.Json.Serialization.JsonPropertyName("id")] public int Id { get; set; } [System.Text.Json.Serialization.JsonPropertyName("title")] public AnilistTitle? Title { get; set; } [System.Text.Json.Serialization.JsonPropertyName("coverImage")] public AnilistCoverImage? CoverImage { get; set; } [System.Text.Json.Serialization.JsonPropertyName("studios")] public AnilistStudioContainer? Studios { get; set; } }
public class AnilistStudioContainer { [System.Text.Json.Serialization.JsonPropertyName("nodes")] public List<AnilistStudioNode>? Nodes { get; set; } }
public class AnilistStudioNode { [System.Text.Json.Serialization.JsonPropertyName("name")] public string? Name { get; set; } }
