CREATE TABLE Fluxos (
    FluxoID INT IDENTITY(1,1) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    DataCriacao DATETIME DEFAULT GETDATE()
);

CREATE TABLE FluxoNodes (
    NodeID VARCHAR(50) PRIMARY KEY,
    FluxoID INT NOT NULL FOREIGN KEY REFERENCES Fluxos(FluxoID) ON DELETE CASCADE,
    Tipo VARCHAR(20) NOT NULL,
    Label VARCHAR(100) NOT NULL,
    PosX INT NOT NULL,
    PosY INT NOT NULL
);

CREATE TABLE FluxoConexoes (
    ConnectionID VARCHAR(50) PRIMARY KEY,
    FluxoID INT NOT NULL FOREIGN KEY REFERENCES Fluxos(FluxoID) ON DELETE CASCADE,
    SourceNodeID VARCHAR(50) NOT NULL,
    SourcePortID VARCHAR(50) NOT NULL,
    TargetNodeID VARCHAR(50) NOT NULL,
    TargetPortID VARCHAR(50) NOT NULL
);
