CREATE TABLE Tags (
    TagID INT IDENTITY(1,1) PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE FranquiaTags (
    FranquiaID INT NOT NULL FOREIGN KEY REFERENCES Franquias(FranquiaID) ON DELETE CASCADE,
    TagID INT NOT NULL FOREIGN KEY REFERENCES Tags(TagID) ON DELETE CASCADE,
    PRIMARY KEY (FranquiaID, TagID)
);
