CREATE TABLE Alertas (
    AlertaID INT IDENTITY(1,1) PRIMARY KEY,
    FranquiaID INT NOT NULL FOREIGN KEY REFERENCES Franquias(FranquiaID) ON DELETE CASCADE,
    FluxoID INT NOT NULL FOREIGN KEY REFERENCES Fluxos(FluxoID) ON DELETE CASCADE,
    Mensagem VARCHAR(255) NOT NULL,
    DataAlerta DATETIME DEFAULT GETDATE(),
    Lido BIT DEFAULT 0
);
